version: '2.1'
services:
    resource-server:
        container_name: resource-server
        build:
          context: './BM-Resource'
          dockerfile: Dockerfile
        volumes:
          - ./BM-Resource/shared:/hostStorage
        ports:
            - "8081:8081"
        depends_on:
          keycloak:
            condition: service_healthy
          mysql:
            condition: service_healthy
        restart: unless-stopped
    keycloak:
        container_name: keycloak
        build:
          context: './BM-Authorization'
          dockerfile: Dockerfile
        ports:
          - "8080:8080"
          - "8443:8443"
        volumes:
          - ./BM-Authorization/shared:/hostStorage
        healthcheck:
          test: ["CMD","curl","-f","http://keycloak:8080/auth/realms/master"]
          interval: 10s
          timeout: 5s
          retries: 20
        depends_on:
          mysql:
            condition: service_healthy
        restart: unless-stopped
    mysql:
        container_name: mysql
        build:
          context: ./MySQL
          dockerfile: Dockerfile
        volumes:
         - ./MySQL/shared:/var/lib/mysql
        ports:
          - "3306:3306"
        healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 10s
          retries: 20
        restart: unless-stopped
